# Generated by Django 5.0.1 on 2025-09-02 16:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("free", "Free"),
                        ],
                        db_index=True,
                        default="stripe",
                        max_length=20,
                    ),
                ),
                ("client_secret", models.CharField(blank=True, max_length=500)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "payment_intents",
                "permissions": (
                    ("payment_intents_rls", "Row Level Security for payment intents"),
                ),
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount after fees", max_digits=10
                    ),
                ),
                (
                    "stripe_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("payment_method_details", models.JSONField(blank=True, default=dict)),
                ("receipt_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("enrollment_created", models.BooleanField(default=False)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transaction",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "payment_intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "permissions": (
                    (
                        "payment_transactions_rls",
                        "Row Level Security for payment transactions",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "refund_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_refunds",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_refunds",
                "permissions": (
                    ("payment_refunds_rls", "Row Level Security for payment refunds"),
                ),
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "default_payment_method",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "stripe_customers",
                "permissions": (
                    ("stripe_customers_rls", "Row Level Security for stripe customers"),
                ),
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("event_data", models.JSONField(default=dict)),
                ("processing_error", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "webhook_events",
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="webhook_eve_stripe__3e5478_idx",
                    ),
                    models.Index(
                        fields=["event_type", "processed"],
                        name="webhook_eve_event_t_f5eefa_idx",
                    ),
                    models.Index(
                        fields=["created_at", "processed"],
                        name="webhook_eve_created_19659d_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["user", "status"], name="payment_int_user_id_f69c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["course", "status"], name="payment_int_course__073fdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="payment_int_stripe__443f7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["created_at", "status"], name="payment_int_created_d66eac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_intent", "status"],
                name="payment_tra_payment_38ef0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["stripe_charge_id"], name="payment_tra_stripe__20b6dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at", "status"], name="payment_tra_created_f775b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["transaction", "status"], name="payment_ref_transac_856cc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["stripe_refund_id"], name="payment_ref_stripe__4c8a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["created_at", "status"], name="payment_ref_created_6c0cfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripecustomer",
            index=models.Index(fields=["user"], name="stripe_cust_user_id_d9067f_idx"),
        ),
        migrations.AddIndex(
            model_name="stripecustomer",
            index=models.Index(
                fields=["stripe_customer_id"], name="stripe_cust_stripe__2ea2de_idx"
            ),
        ),
    ]
