# Generated by Django 5.0.1 on 2025-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='subtitles',
            field=models.URLField(blank=True, help_text='CDN URL of the SRT subtitle file uploaded to Backblaze', max_length=1000, null=True),
        ),
    ]
