# Generated by Django 5.0.1 on 2025-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_optimize_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="idx_published_status_created",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="idx_instructor_courses",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="idx_category_published",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="idx_free_price",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="idx_rating",
        ),
        migrations.RemoveIndex(
            model_name="coursesection",
            name="idx_course_section_order",
        ),
    ]
