# Generated by Django 5.0.1 on 2025-09-02 16:02

import app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleReflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who created this",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who last updated this",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.UUIDField(
                        blank=True,
                        help_text="Supabase User ID who deleted this",
                        null=True,
                    ),
                ),
                (
                    "reflection_type",
                    models.CharField(
                        choices=[
                            ("voice", "Voice Reflection"),
                            ("image", "Image Reflection"),
                            ("loom_link", "Loom Video Link"),
                        ],
                        db_index=True,
                        default="voice",
                        max_length=20,
                    ),
                ),
                (
                    "loom_link",
                    models.URLField(
                        blank=True, help_text="Optional Loom video link", null=True
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        help_text="Optional text reflection content",
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puzzle_reflections",
                        to="courses.course",
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uploaded reflection media file (video/audio/document)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puzzle_reflections",
                        to="media_library.mediafile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this reflection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzle_reflections",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "video_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Video MediaFile this reflection is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_reflections",
                        to="media_library.mediafile",
                    ),
                ),
            ],
            options={
                "db_table": "puzzle_reflections",
                "ordering": ["-created_at"],
                "permissions": (
                    (
                        "puzzle_reflections_rls",
                        "Row Level Security for puzzle reflections",
                    ),
                ),
                "indexes": [
                    models.Index(
                        fields=["user", "video_id"],
                        name="puzzle_refl_user_id_ab0770_idx",
                    ),
                    models.Index(
                        fields=["reflection_type"],
                        name="puzzle_refl_reflect_8c439d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="puzzle_refl_created_6f2b94_idx"
                    ),
                    models.Index(
                        fields=["media_file"], name="puzzle_refl_media_f_880b93_idx"
                    ),
                    models.Index(
                        fields=["course", "user"], name="puzzle_refl_course__5da3ba_idx"
                    ),
                ],
            },
            bases=(models.Model, app.models.RLSModelMixin),
        ),
    ]
