# Generated by Django 5.0.1 on 2025-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_reflections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlereflection',
            name='reflection_type',
            field=models.CharField(choices=[('voice', 'Voice Reflection'), ('image', 'Image Reflection'), ('loom_link', 'Loom Video Link')], db_index=True, default='voice', max_length=20),
        ),
    ]
