# Generated by Django 5.0.1 on 2025-08-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediafile_subtitles'),
        ('puzzle_reflections', '0002_update_reflection_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='puzzlereflection',
            new_name='puzzle_refl_user_id_ab0770_idx',
            old_name='puzzle_refl_user_id_b4818c_idx',
        ),
        migrations.AlterField(
            model_name='puzzlereflection',
            name='video_id',
            field=models.ForeignKey(help_text='Video MediaFile this reflection is for', on_delete=django.db.models.deletion.CASCADE, related_name='video_reflections', to='media_library.mediafile'),
        ),
    ]
