# Generated by Django 5.0.1 on 2025-09-02 16:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Role Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "permissions",
                    models.JSONField(default=list, verbose_name="Permissions"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Plan ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Plan Description"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Monthly Price",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Yearly Price",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe Product ID"
                    ),
                ),
                (
                    "stripe_price_monthly_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe Monthly Price ID",
                    ),
                ),
                (
                    "stripe_price_yearly_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe Yearly Price ID",
                    ),
                ),
                (
                    "ai_daily_limit",
                    models.IntegerField(
                        default=0, verbose_name="Daily AI Interactions Limit"
                    ),
                ),
                (
                    "ai_monthly_limit",
                    models.IntegerField(
                        default=0, verbose_name="Monthly AI Interactions Limit"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with feature flags",
                        verbose_name="Plan Features",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured Plan"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Display Sort Order"),
                ),
                (
                    "trial_days",
                    models.IntegerField(default=0, verbose_name="Trial Period (days)"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "supabase_user_id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Supabase User ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Full Name"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Display Name"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="Avatar URL")),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Language"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Login"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
                "indexes": [
                    models.Index(
                        fields=["email", "status"], name="user_profil_email_588a91_idx"
                    ),
                    models.Index(
                        fields=["username", "status"],
                        name="user_profil_usernam_b78501_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("upgrade", "Upgrade"),
                            ("downgrade", "Downgrade"),
                            ("cancel", "Cancel"),
                            ("resume", "Resume"),
                            ("pause", "Pause"),
                            ("expire", "Expire"),
                            ("trial_start", "Trial Start"),
                            ("trial_end", "Trial End"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_success", "Payment Success"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Reason for Change"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe Event ID"
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe Invoice ID"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Metadata"
                    ),
                ),
                (
                    "from_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_from",
                        to="accounts.subscriptionplan",
                        verbose_name="From Plan",
                    ),
                ),
                (
                    "to_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_to",
                        to="accounts.subscriptionplan",
                        verbose_name="To Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to="accounts.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription History",
                "verbose_name_plural": "Subscription History",
                "db_table": "subscription_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="subscriptio_user_id_a61562_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="subscriptio_action_883832_idx",
                    ),
                    models.Index(
                        fields=["stripe_event_id"],
                        name="subscriptio_stripe__673d52_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "session_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Session Token"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "sessions",
                "indexes": [
                    models.Index(
                        fields=["session_token"], name="sessions_session_7633cd_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="sessions_user_id_85103c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "assigned_by",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Assigned By User ID"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("past_due", "Past Due"),
                            ("trialing", "Trialing"),
                            ("expired", "Expired"),
                            ("paused", "Paused"),
                            ("incomplete", "Incomplete"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                        verbose_name="Billing Period",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Current Period Start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="Current Period End"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, verbose_name="Cancel at Period End"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Canceled At"
                    ),
                ),
                (
                    "trial_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial Start Date"
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial End Date"
                    ),
                ),
                (
                    "ai_usage_this_period",
                    models.IntegerField(default=0, verbose_name="AI Usage This Period"),
                ),
                (
                    "ai_usage_today",
                    models.IntegerField(default=0, verbose_name="AI Usage Today"),
                ),
                (
                    "last_usage_reset_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Last Usage Reset Date"
                    ),
                ),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Last Payment Amount",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Payment Date"
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Payment Date"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Metadata"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.subscriptionplan",
                        verbose_name="Subscription Plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "db_table": "user_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["status", "current_period_end"],
                        name="user_subscr_status_db025e_idx",
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="user_subscr_stripe__2076b6_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="user_subscr_user_id_c57286_idx"
                    ),
                ],
            },
        ),
    ]
