# Generated by Django 5.0.1 on 2025-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_optimize_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="role",
            name="idx_role_active",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="idx_supabase_user_id",
        ),
        migrations.RemoveIndex(
            model_name="userrole",
            name="idx_user_role",
        ),
    ]
